// Auto-generated by generate-content-schema.ts
// Source: ch_ui_export_2026-02-20T11-16-05.json
// Generated: 2026-02-20T11:19:37.531Z
//
// 10331 content lines across 7 types

import { z } from "zod";

export const assistantSchema = z.object({
	parentUuid: z.string(),
	isSidechain: z.boolean(),
	userType: z.string(),
	cwd: z.string(),
	sessionId: z.string(),
	version: z.string(),
	gitBranch: z.string(),
	message: z.object({
		model: z.string(),
		id: z.string(),
		type: z.string(),
		role: z.string(),
		content: z.array(
			z.object({
				type: z.string(),
				text: z.string().nullable(),
				id: z.string().nullable(),
				name: z.string().nullable(),
				input: z
					.object({
						command: z.string().nullable(),
						description: z.string().nullable(),
						prompt: z.string().nullable(),
						subagent_type: z.string().nullable(),
						pattern: z.string().nullable(),
						path: z.string().nullable(),
						file_path: z.string().nullable(),
						content: z.string().nullable(),
						todos: z
							.array(
								z.object({
									content: z.string(),
									status: z.string(),
									activeForm: z.string(),
								}),
							)
							.nullable(),
						task_id: z.string().nullable(),
						block: z.boolean().nullable(),
						timeout: z.number().int().nullable(),
						replace_all: z.boolean().nullable(),
						old_string: z.string().nullable(),
						new_string: z.string().nullable(),
						query: z.string().nullable(),
						url: z.string().nullable(),
						skill: z.string().nullable(),
						args: z.string().nullable(),
					})
					.nullable(),
				thinking: z.string().nullable(),
				signature: z.string().nullable(),
				caller: z
					.object({
						type: z.string(),
					})
					.nullable(),
			}),
		),
		stop_reason: z.string().nullable(),
		stop_sequence: z.string().nullable(),
		usage: z.object({
			input_tokens: z.number().int(),
			cache_creation_input_tokens: z.number().int(),
			cache_read_input_tokens: z.number().int(),
			cache_creation: z.object({
				ephemeral_5m_input_tokens: z.number().int(),
				ephemeral_1h_input_tokens: z.number().int(),
			}),
			output_tokens: z.number().int(),
			service_tier: z.string().nullable(),
			server_tool_use: z
				.object({
					web_search_requests: z.number().int(),
					web_fetch_requests: z.number().int(),
				})
				.nullable(),
			inference_geo: z.string().nullable(),
			iterations: z.unknown().nullable(),
			speed: z.unknown().nullable(),
		}),
		context_management: z.unknown().nullable(),
		container: z.unknown().nullable(),
	}),
	requestId: z.string().nullable(),
	type: z.literal("assistant"),
	uuid: z.string(),
	timestamp: z.string(),
	slug: z.string().nullable(),
	error: z.string().nullable(),
	isApiErrorMessage: z.boolean().nullable(),
});
export type Assistant = z.infer<typeof assistantSchema>;

export const file_history_snapshotSchema = z.object({
	type: z.literal("file-history-snapshot"),
	messageId: z.string(),
	snapshot: z.object({
		messageId: z.string(),
		trackedFileBackups: z.record(
			z.string(),
			z.object({
				backupFileName: z.string().nullable(),
				version: z.number().int(),
				backupTime: z.string(),
			}),
		),
		timestamp: z.string(),
	}),
	isSnapshotUpdate: z.boolean(),
});
export type File_history_snapshot = z.infer<typeof file_history_snapshotSchema>;

export const progressSchema = z.object({
	parentUuid: z.string(),
	isSidechain: z.boolean(),
	userType: z.string(),
	cwd: z.string(),
	sessionId: z.string(),
	version: z.string(),
	gitBranch: z.string(),
	slug: z.string(),
	type: z.literal("progress"),
	data: z.object({
		type: z.string(),
		hookEvent: z.string().nullable(),
		hookName: z.string().nullable(),
		command: z.string().nullable(),
		output: z.string().nullable(),
		fullOutput: z.string().nullable(),
		elapsedTimeSeconds: z.number().int().nullable(),
		totalLines: z.number().int().nullable(),
		message: z
			.object({
				type: z.string(),
				message: z.object({
					role: z.string(),
					content: z.array(
						z.object({
							type: z.string(),
							text: z.string().nullable(),
							id: z.string().nullable(),
							name: z.string().nullable(),
							input: z.record(z.string(), z.string()).nullable(),
							tool_use_id: z.string().nullable(),
							content: z.string().nullable(),
							is_error: z.boolean().nullable(),
						}),
					),
					model: z.string().nullable(),
					id: z.string().nullable(),
					type: z.string().nullable(),
					stop_reason: z.unknown().nullable(),
					stop_sequence: z.unknown().nullable(),
					usage: z
						.object({
							input_tokens: z.number().int(),
							cache_creation_input_tokens: z.number().int(),
							cache_read_input_tokens: z.number().int(),
							cache_creation: z.object({
								ephemeral_5m_input_tokens: z.number().int(),
								ephemeral_1h_input_tokens: z.number().int(),
							}),
							output_tokens: z.number().int(),
							service_tier: z.string(),
						})
						.nullable(),
					context_management: z.unknown().nullable(),
				}),
				uuid: z.string(),
				timestamp: z.string(),
				requestId: z.string().nullable(),
				toolUseResult: z
					.union([
						z.object({
							mode: z.string().nullable(),
							filenames: z.array(z.string()).nullable(),
							numFiles: z.number().int().nullable(),
							durationMs: z.number().int().nullable(),
							truncated: z.boolean().nullable(),
							stdout: z.string().nullable(),
							stderr: z.string().nullable(),
							interrupted: z.boolean().nullable(),
							isImage: z.boolean().nullable(),
							type: z.string().nullable(),
							file: z
								.object({
									filePath: z.string(),
									content: z.string(),
									numLines: z.number().int(),
									startLine: z.number().int(),
									totalLines: z.number().int(),
								})
								.nullable(),
						}),
						z.string(),
					])
					.nullable(),
			})
			.nullable(),
		normalizedMessages: z
			.array(
				z.object({
					type: z.string(),
					message: z
						.object({
							role: z.string(),
							content: z.array(
								z.object({
									type: z.string(),
									text: z.string().nullable(),
									id: z.string().nullable(),
									name: z.string().nullable(),
									input: z.record(z.string(), z.string()).nullable(),
									tool_use_id: z.string().nullable(),
									content: z.string().nullable(),
									is_error: z.boolean().nullable(),
								}),
							),
							model: z.string().nullable(),
							id: z.string().nullable(),
							type: z.string().nullable(),
							stop_reason: z.unknown().nullable(),
							stop_sequence: z.unknown().nullable(),
							usage: z
								.object({
									input_tokens: z.number().int(),
									cache_creation_input_tokens: z.number().int(),
									cache_read_input_tokens: z.number().int(),
									cache_creation: z.object({
										ephemeral_5m_input_tokens: z.number().int(),
										ephemeral_1h_input_tokens: z.number().int(),
									}),
									output_tokens: z.number().int(),
									service_tier: z.string(),
								})
								.nullable(),
							context_management: z.unknown().nullable(),
						})
						.nullable(),
					uuid: z.string(),
					timestamp: z.string(),
					requestId: z.string().nullable(),
					toolUseResult: z
						.union([
							z.object({
								mode: z.string().nullable(),
								filenames: z.array(z.string()).nullable(),
								numFiles: z.number().int().nullable(),
								durationMs: z.number().int().nullable(),
								truncated: z.boolean().nullable(),
								stdout: z.string().nullable(),
								stderr: z.string().nullable(),
								interrupted: z.boolean().nullable(),
								isImage: z.boolean().nullable(),
								type: z.string().nullable(),
								file: z
									.object({
										filePath: z.string(),
										content: z.string(),
										numLines: z.number().int(),
										startLine: z.number().int(),
										totalLines: z.number().int(),
									})
									.nullable(),
							}),
							z.string(),
						])
						.nullable(),
					attachment: z
						.object({
							type: z.string(),
							content: z.union([z.string(), z.array(z.unknown().nullable())]),
							itemCount: z.number().int().nullable(),
							hookName: z.string().nullable(),
							toolUseID: z.string().nullable(),
							hookEvent: z.string().nullable(),
						})
						.nullable(),
					data: z
						.object({
							type: z.string(),
							hookEvent: z.string().nullable(),
							hookName: z.string().nullable(),
							command: z.string().nullable(),
							output: z.string().nullable(),
							fullOutput: z.string().nullable(),
							elapsedTimeSeconds: z.number().int().nullable(),
							totalLines: z.number().int().nullable(),
						})
						.nullable(),
					toolUseID: z.string().nullable(),
					parentToolUseID: z.string().nullable(),
				}),
			)
			.nullable(),
		prompt: z.string().nullable(),
		agentId: z.string().nullable(),
		timeoutMs: z.number().int().nullable(),
		taskDescription: z.string().nullable(),
		taskType: z.string().nullable(),
	}),
	toolUseID: z.string(),
	parentToolUseID: z.string(),
	uuid: z.string(),
	timestamp: z.string(),
});
export type Progress = z.infer<typeof progressSchema>;

export const queue_operationSchema = z.object({
	type: z.literal("queue-operation"),
	operation: z.string(),
	timestamp: z.string(),
	sessionId: z.string(),
	content: z.string().nullable(),
});
export type Queue_operation = z.infer<typeof queue_operationSchema>;

export const summarySchema = z.object({
	type: z.literal("summary"),
	summary: z.string(),
	leafUuid: z.string(),
});
export type Summary = z.infer<typeof summarySchema>;

export const systemSchema = z.object({
	parentUuid: z.string().nullable(),
	isSidechain: z.boolean(),
	userType: z.string(),
	cwd: z.string(),
	sessionId: z.string(),
	version: z.string(),
	gitBranch: z.string(),
	slug: z.string(),
	type: z.literal("system"),
	subtype: z.string(),
	hookCount: z.number().int().nullable(),
	hookInfos: z
		.array(
			z.object({
				command: z.string(),
			}),
		)
		.nullable(),
	hookErrors: z.array(z.unknown().nullable()).nullable(),
	preventedContinuation: z.boolean().nullable(),
	stopReason: z.string().nullable(),
	hasOutput: z.boolean().nullable(),
	level: z.string(),
	timestamp: z.string(),
	uuid: z.string(),
	toolUseID: z.string().nullable(),
	logicalParentUuid: z.string().nullable(),
	content: z.string().nullable(),
	isMeta: z.boolean().nullable(),
	compactMetadata: z
		.object({
			trigger: z.string(),
			preTokens: z.number().int(),
		})
		.nullable(),
});
export type System = z.infer<typeof systemSchema>;

export const userSchema = z.object({
	parentUuid: z.string().nullable(),
	isSidechain: z.boolean(),
	userType: z.string(),
	cwd: z.string(),
	sessionId: z.string(),
	version: z.string(),
	gitBranch: z.string(),
	type: z.literal("user"),
	message: z.object({
		role: z.string(),
		content: z.union([
			z.array(
				z.object({
					type: z.string(),
					text: z.string().nullable(),
					content: z.string().nullable(),
					is_error: z.boolean().nullable(),
					tool_use_id: z.string().nullable(),
				}),
			),
			z.string(),
		]),
	}),
	uuid: z.string(),
	timestamp: z.string(),
	toolUseResult: z
		.union([
			z.string(),
			z.object({
				filenames: z.array(z.string()).nullable(),
				durationMs: z.number().int().nullable(),
				numFiles: z.number().int().nullable(),
				truncated: z.boolean().nullable(),
				type: z.string().nullable(),
				file: z
					.object({
						filePath: z.string(),
						content: z.string(),
						numLines: z.number().int(),
						startLine: z.number().int(),
						totalLines: z.number().int(),
					})
					.nullable(),
				stdout: z.string().nullable(),
				stderr: z.string().nullable(),
				interrupted: z.boolean().nullable(),
				isImage: z.boolean().nullable(),
				oldTodos: z
					.array(
						z.object({
							content: z.string(),
							status: z.string(),
							activeForm: z.string(),
						}),
					)
					.nullable(),
				newTodos: z
					.array(
						z.object({
							content: z.string(),
							status: z.string(),
							activeForm: z.string(),
						}),
					)
					.nullable(),
				filePath: z.string().nullable(),
				content: z.string().nullable(),
				structuredPatch: z
					.array(
						z.object({
							oldStart: z.number().int(),
							oldLines: z.number().int(),
							newStart: z.number().int(),
							newLines: z.number().int(),
							lines: z.array(z.string()),
						}),
					)
					.nullable(),
				originalFile: z.string().nullable(),
				backgroundTaskId: z.string().nullable(),
				retrieval_status: z.string().nullable(),
				task: z
					.object({
						task_id: z.string(),
						task_type: z.string(),
						status: z.string(),
						description: z.string(),
						output: z.string(),
						exitCode: z.number().int().nullable(),
					})
					.nullable(),
				oldString: z.string().nullable(),
				newString: z.string().nullable(),
				userModified: z.boolean().nullable(),
				replaceAll: z.boolean().nullable(),
				query: z.string().nullable(),
				results: z
					.array(
						z.union([
							z.object({
								tool_use_id: z.string(),
								content: z.array(
									z.object({
										title: z.string(),
										url: z.string(),
									}),
								),
							}),
							z.string(),
						]),
					)
					.nullable(),
				durationSeconds: z.number().nullable(),
				bytes: z.number().int().nullable(),
				code: z.number().int().nullable(),
				codeText: z.string().nullable(),
				result: z.string().nullable(),
				url: z.string().nullable(),
				noOutputExpected: z.boolean().nullable(),
				success: z.boolean().nullable(),
				commandName: z.string().nullable(),
			}),
		])
		.nullable(),
	sourceToolAssistantUUID: z.string().nullable(),
	slug: z.string().nullable(),
	todos: z
		.array(
			z.object({
				content: z.string(),
				status: z.string(),
				activeForm: z.string(),
			}),
		)
		.nullable(),
	isVisibleInTranscriptOnly: z.boolean().nullable(),
	isCompactSummary: z.boolean().nullable(),
	permissionMode: z.string().nullable(),
	isMeta: z.boolean().nullable(),
	sourceToolUseID: z.string().nullable(),
});
export type User = z.infer<typeof userSchema>;

export const contentLineSchema = z.discriminatedUnion("type", [
	assistantSchema,
	file_history_snapshotSchema,
	progressSchema,
	queue_operationSchema,
	summarySchema,
	systemSchema,
	userSchema,
]);
export type ContentLine = z.infer<typeof contentLineSchema>;
